Gp 22 fe dash board
FPTU-GHub-Capstone/ghub-app pull request #5
Opened 2023-10-03 13:11 UTC by dg-panh

New features:

- Logic routers
- Layout components

2023-10-03 17:02 UTC, danielNg91 requested changes

2023-10-03 17:02 UTC, danielNg91 commented on src/common/constant.ts
> +	LOGIN: 'Login',
use enum or Object.Freeze to prevent runtime change value of PageName

2023-10-03 17:02 UTC, danielNg91 commented on src/common/constant.ts
> +	const path = {
same as above

2023-10-03 17:02 UTC, danielNg91 commented on src/components/Scrollbar/Scrollbar.tsx
> +	children: Array<ReactElement | any>,
why use any here?

2023-10-03 17:02 UTC, danielNg91 commented on src/hooks/useResponsive.ts
> +	if (query === 'up') {
use switch case and map these values of query to enum

2023-10-03 17:02 UTC, danielNg91 commented on src/Layout/DashboardLayout/Sidebar/Sidebar.tsx
> +const renderContent = (
component hell. Split to smaller components

2023-10-04 08:33 UTC, dg-panh commented on src/components/Scrollbar/Scrollbar.tsx
> +	children: Array<ReactElement | any>,
I have issue when try to pass children props into this component but I had fixed it and forgot delete any type

2023-10-04 08:36 UTC, dg-panh commented on src/hooks/useResponsive.ts
> +	if (query === 'up') {
@@ thoi no need nha

2023-10-04 10:24 UTC, danielNg91 requested changes

2023-10-04 10:24 UTC, danielNg91 commented on src/utils/cssStyles.ts
> -export function bgBlur(props: Props) {
just recommend, `bgBlur(props?: Props): object` is the same as 2 times Type Assertion

2023-10-04 10:24 UTC, danielNg91 commented on src/common/constant.ts
> +export const AppPath = (pageName: string) => {
use enum PageName{}   
export const AppPath = (pageName: PageName)

2023-10-04 10:24 UTC, danielNg91 commented on src/common/constant.ts
> +export const AppPath = (pageName: string) => {
why this function use PascalCase?

2023-10-04 10:27 UTC, dg-panh commented on src/common/constant.ts
> +export const AppPath = (pageName: string) => {
ủa sao kiu dùng object.freeze cũn dc xong h đổi í hã ~.~

2023-10-04 15:20 UTC, danielNg91 approved these changes

2023-10-04 15:25 UTC, danielNg91 commented on src/hooks/useResponsive.ts
> +	if (query === 'up') {
sao ko?? :v

2023-10-04 15:29 UTC, danielNg91 requested changes

2023-10-04 15:29 UTC, danielNg91 commented on src/common/constant.ts
> +		[PageName.LOGIN]: '/login',
use global var to optimize performance:
const pathMap = new Map<string, string>(
[
[PageName.REGISTER,  '/register'],
[PageName.LANDING_PAGE: '/landingPage'],
...
]
)
export const convertNameToPath = (pageName: PageName) => pathMap.get(pageName)

2023-10-05 02:13 UTC, danielNg91 approved these changes

2023-10-05 03:49 UTC, merged